// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFSA0Z3fXsL64kTO7owS7bSwfVMVtn13s',
    appId: '1:976618334884:web:f2e16c38f6cf529a97d431',
    messagingSenderId: '976618334884',
    projectId: 'fir-one-eff08',
    authDomain: 'fir-one-eff08.firebaseapp.com',
    storageBucket: 'fir-one-eff08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNfvMndRgPyw8DOVzrFjtJrtPDYygfsB8',
    appId: '1:976618334884:android:cfb888542d1bf1f997d431',
    messagingSenderId: '976618334884',
    projectId: 'fir-one-eff08',
    storageBucket: 'fir-one-eff08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEweN7SE881Bg8yYJKc6ZdB6CFd4GvSKI',
    appId: '1:976618334884:ios:75c2e790efb4d46b97d431',
    messagingSenderId: '976618334884',
    projectId: 'fir-one-eff08',
    storageBucket: 'fir-one-eff08.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEweN7SE881Bg8yYJKc6ZdB6CFd4GvSKI',
    appId: '1:976618334884:ios:9eef8d92daaf194997d431',
    messagingSenderId: '976618334884',
    projectId: 'fir-one-eff08',
    storageBucket: 'fir-one-eff08.appspot.com',
    iosBundleId: 'com.example.firebase2.RunnerTests',
  );
}
